Leer Archivos

In [2]:
import os
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Ruta de la carpeta
folder_path = r"C:\Users\kevin\OneDrive\Documentos\GitHub\ProyectoRI\data\preprocessed_txt"

# Leer los archivos de texto en la carpeta
texts = [open(os.path.join(folder_path, filename), 'r', encoding='utf-8').read()
         for filename in os.listdir(folder_path) if filename.endswith(".txt")]

In [3]:
len(texts)

3019

# Vectorización usando Bag of Words (BoW)

In [10]:
vectorizer_bow = CountVectorizer()
X_bow = vectorizer_bow.fit_transform(texts)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

# Suponiendo que 'texts' es una variable que contiene tus textos

# Inicializar el vectorizador
vectorizer_bow = CountVectorizer()

# Vectorizar los textos
X_bow = vectorizer_bow.fit_transform(texts)

# Imprimir los resultados
print("Matriz de términos y documentos:")
print(X_bow.toarray())

# Imprimir el vocabulario
print("Vocabulario:")
print(vectorizer_bow.vocabulary_)


Matriz de términos y documentos:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Vocabulario:
{'asian': 7669, 'export': 10389, 'fear': 10505, 'damag': 9398, 'usjapan': 19072, 'rift': 16999, 'mount': 15078, 'trade': 18640, 'friction': 10834, 'japan': 12066, 'rais': 16564, 'asia': 7668, 'nation': 15185, 'row': 17111, 'inflict': 11815, 'farreach': 10475, 'econom': 10019, 'businessmen': 8405, 'offici': 15521, 'told': 18584, 'reuter': 16938, 'correspond': 9206, 'capit': 8500, 'move': 15084, 'boost': 8166, 'protectionist': 16421, 'sentiment': 17428, 'lead': 12480, 'curb': 9338, 'american': 7432, 'import': 11721, 'product': 16379, 'conflict': 9063, 'hurt': 11629, 'longrun': 12672, 'shortterm': 17559, 'tokyo': 18583, 'loss': 12689, 'gain': 10906, 'impos': 11724, '300': 3175, 'mln': 14970, 'dlrs': 9810, 'tariff': 18333, 'japanes': 12067, 'electron': 10096, 'good': 11096, 'april': 7574, '17': 1458, 'retali': 16925, 'alleg': 

# Vectorización usando TF-IDF

In [5]:
vectorizer_tfidf = TfidfVectorizer()
X_tfidf = vectorizer_tfidf.fit_transform(texts)

# Similitud entre consulta BoW

In [6]:
query = "japan revis longterm energi demand ministri"
# Vectorización de la consulta utilizando el vectorizador BoW
query_vector_bow = vectorizer_bow.transform([query])

# Calcular la similitud entre la consulta y los documentos utilizando BoW
similarity_scores_bow = cosine_similarity(query_vector_bow, X_bow)

# Obtener los documentos ordenados por similitud
ranked_documents_bow = np.argsort(similarity_scores_bow)[0][::-1]

# Mostrar solo los primeros 10 resultados
for i, doc_index in enumerate(ranked_documents_bow[:10]):  # Solo los primeros 10 resultados
    print(f"Resultado {i+1}: Documento {doc_index}, Similitud: {similarity_scores_bow[0][doc_index]}")
    print(texts[doc_index][:200])  # Mostrar los primeros 200 caracteres del documento
    print()


Resultado 1: Documento 2, Similitud: 0.5326236412913076
japan revis longterm energi demand ministri intern trade industri miti revis longterm energi supplydemand outlook august meet forecast downtrend japanes energi demand ministri offici miti expect lower

Resultado 2: Documento 14, Similitud: 0.28545680510919436
japan ministri open farm trade hit japan agricultur ministri anger demand japan open farm product market offici talk month liberalis harm exist farm export japan senior ministri offici import drop due

Resultado 3: Documento 284, Similitud: 0.2810497136596714
econom spotlight telecom key japan ministri japan littleknown ministri post telecommun mpt emerg intern forc reckon polit analyst mpt thrust spotlight trade row britain posit strength due control lucr

Resultado 4: Documento 282, Similitud: 0.2769103481957583
japan ministri comment rice talk report agricultur ministri declin comment local newspap report japan agre hold talk close rice market gatt round idea report commen

# Similitud entre consulta TF-IDF

In [7]:
query = "japan revis longterm energi demand ministri"

# Vectorización de la consulta utilizando el vectorizador TF-IDF
query_vector_tfidf = vectorizer_tfidf.transform([query])

# Calcular la similitud entre la consulta y los documentos utilizando TF-IDF
similarity_scores_tfidf = cosine_similarity(query_vector_tfidf, X_tfidf)

# Obtener los documentos ordenados por similitud
ranked_documents_tfidf = np.argsort(similarity_scores_tfidf)[0][::-1]

# Mostrar solo los primeros 10 resultados
for i, doc_index in enumerate(ranked_documents_tfidf[:10]):  # Solo los primeros 10 resultados
    print(f"Resultado {i+1}: Documento {doc_index}, Similitud: {similarity_scores_tfidf[0][doc_index]}")
    print(texts[doc_index][:200])  # Mostrar los primeros 200 caracteres del documento
    print()



Resultado 1: Documento 2, Similitud: 0.5094756136643848
japan revis longterm energi demand ministri intern trade industri miti revis longterm energi supplydemand outlook august meet forecast downtrend japanes energi demand ministri offici miti expect lower

Resultado 2: Documento 14, Similitud: 0.22764948233074192
japan ministri open farm trade hit japan agricultur ministri anger demand japan open farm product market offici talk month liberalis harm exist farm export japan senior ministri offici import drop due

Resultado 3: Documento 284, Similitud: 0.2042519891373625
econom spotlight telecom key japan ministri japan littleknown ministri post telecommun mpt emerg intern forc reckon polit analyst mpt thrust spotlight trade row britain posit strength due control lucr

Resultado 4: Documento 282, Similitud: 0.20306267500430591
japan ministri comment rice talk report agricultur ministri declin comment local newspap report japan agre hold talk close rice market gatt round idea report comme